config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  #Normal Routes
  
  root 'table_links#index'
  get 'table_links/about'

  #Modal Routes
  resources :reservations

  # resources :tables
  # resources :restaurants
  # resources :restaurants do
  #   resources :tables, only: [:new, :create, :destroy]
  # end

  resources :restaurants do
    resources :tables do
      resources :reservations, only: [:index, :new, :create]
    end
  end
  
  get 'my_restaurants', to: 'restaurants#my_restaurants'
  get 'my_reservations', to: 'reservations#my_reservations'
  
  #Devise Routes
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validate :validate_unique_reservation

  belongs_to :user
  belongs_to :restaurant
  belongs_to :table
  
  private

  #Validation Control for Time Limits
  def validate_unique_reservation
    if Reservation.exists?(restaurant_id: restaurant_id, table_id: table_id, reservation_date: reservation_date)
      errors.add(:base, "Another reservation already exists for the same restaurant, table, and time frame")
    end
  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :authorize_customer, only: [:new, :create]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = current_user.reservations.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy!

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def my_reservations
    @reservations = current_user.reservations if current_user.role == "Customer"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:reservation_name, :reservation_date, :is_active, :user_id, :restaurant_id, :table_id)
    end

    def authorize_customer
      unless current_user && current_user.role == "Customer"
        flash[:alert] = "You are not authorized to access this page."
        redirect_to root_path
      end
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :reservation_name, style: "display: block" %>
    <%= form.text_field :reservation_name %>
  </div>

  <div>
    <%= form.label :reservation_date, style: "display: block" %>
    <%= form.datetime_field :reservation_date %>
  </div>

  <div>
    <%= form.label :is_active, style: "display: block" %>
    <%= form.check_box :is_active %>
  </div>

  <!-- Restaurant selection dropdown -->
  <div>
    <%= form.label :restaurant_id, 'Restaurant', style: "display: block" %>
    <%= form.collection_select :restaurant_id, Restaurant.all, :restaurant_name, :restaurant_name, { prompt: 'Select a Restaurant' }, { class: 'restaurant-select' } %>
  </div>

  <!-- Table selection dropdown -->
  <div class="table-dropdown">
    <%= form.label :table_id, 'Table', style: "display: block" %>
    <%= form.collection_select :table_id, [], :id, :table_name, { prompt: 'Select a Table' }, { class: 'table-select' } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>">
  <p>
    <strong>Reservation name:</strong>
    <%= reservation.reservation_name %>
  </p>

  <p>
    <strong>Reservation date:</strong>
    <%= reservation.reservation_date %>
  </p>

  <p>
    <strong>Is active:</strong>
    <%= reservation.is_active %>
  </p>

</div>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show this reservation", @reservation %> |
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reservations</h1>

<% if current_user && current_user.role == 'Customer' %>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Reservation Name</th>
          <th>Restaurant</th>
          <th>Address</th>
          <th>Date and Time</th>
          <th>Table</th>
          <th>Active</th>
          <th>Show</th>
        </tr>
      </thead>
      <tbody>
        <% @reservations.each do |reservation| %>
          <tr>
            <td><%= reservation.reservation_name %></td>
            <td><%= reservation.restaurant.restaurant_name %></td>
            <td><%= reservation.restaurant.address %></td>
            <td><%= reservation.reservation_date.strftime("%Y-%m-%d %H:%M:%S") %></td>
            <td><%= reservation.table.table_name %></td>
            <td><%= reservation.is_active ? 'Yes' : 'No' %></td>
            <td><%= link_to "Show", reservation %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p>No  Reservations Found</p>
<% end %>

<% if current_user && current_user.role == 'Customer' %>
  <div>
    <%= link_to "New reservation", new_reservation_path %>
  </div>
<% end %>

app/views/reservations/my_reservations.html.erb
<h1>My Reservations</h1>

<% if @reservations.any? %>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Reservation ID</th>
          <th>Reservation Name</th>
          <th>Restaurant</th>
          <th>Date and Time</th>
          <!-- Add more headers if needed -->
        </tr>
      </thead>
      <tbody>
        <% @reservations.each do |reservation| %>
          <tr>
            <td><%= reservation.id %></td>
            <td><%= reservation.reservation_name %></td>
            <td><%= reservation.restaurant.restaurant_name %></td>
            <td><%= reservation.reservation_date %></td>
            <!-- Add more cells for additional reservation details -->
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p>You Have not Made Any Reservations.</p>
<% end %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reservation %>

<div>
  <%= link_to "Edit this reservation", edit_reservation_path(@reservation) %> |
  <%= link_to "Back to reservations", reservations_path %>

  <%= button_to "Destroy this reservation", @reservation, method: :delete %>
</div>