config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  #Normal Routes
  
  root 'table_links#index'
  get 'table_links/about'

  #Modal Routes
  resources :reservations

  # resources :tables
  # resources :restaurants
  # resources :restaurants do
  #   resources :tables, only: [:new, :create, :destroy]
  # end

  resources :restaurants do
    resources :tables do
      resources :reservations, only: [:index, :new, :create]
    end
  end
  
  get 'my_restaurants', to: 'restaurants#my_restaurants'
  get 'my_reservations', to: 'reservations#my_reservations'
  
  #Devise Routes
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: %i[ show edit update destroy ]
  before_action :set_restaurant, only: [:new, :create]

  # GET /tables or /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1 or /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = @restaurant.tables.build
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables or /tables.json
  def create
    @table = @restaurant.tables.build(table_params)
  
    respond_to do |format|
      if @table.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Table was successfully created." }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1 or /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: "Table was successfully updated." }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1 or /tables/1.json
  def destroy
    #This line retrieves a specific record from the tables table in the database based on the id parameter 
    #passed in the request. It's commonly used in Rails to fetch a single record by its unique identifier.
    @table = Table.find(params[:id]) 

    #This line retrieves the associated restaurant record for the @table instance. 
    #Assuming there's an association between tables and restaurants tables, this line uses 
    #that association to fetch the related restaurant.
    @restaurant = @table.restaurant

    #This line deletes the @table record from the database. 
    #In Rails, the destroy method not only removes the record from the table but also runs any 
    #associated callbacks and removes associated records if there are any dependent relationships configured.
    @table.destroy

    respond_to do |format|
      format.html { redirect_to restaurant_url(@restaurant), notice: "Table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_params
      params.require(:table).permit(:table_name, :seat_number, :is_available)
    end

    # Define a Restaurant associated with a table
    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_with(model: [restaurant, table]) do |form| %>
  <% if table.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>
      <ul>
        <% table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Other table fields here -->
  <div>
    <%= form.label :table_name, style: "display: block" %>
    <%= form.text_field :table_name %>
  </div>

  <div>
    <%= form.label :seat_number, style: "display: block" %>
    <%= form.text_field :seat_number %>
  </div>

  <div>
    <%# <%=form.label :is_available, style: "display: block"%>
    <%# <%= form.check_box :is_available %>
  </div>

  <%#  %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tables/_table.html.erb
<div id="<%= dom_id table %>">
  <p>
    <strong>Table name:</strong>
    <%= table.table_name %>
  </p>

  <p>
    <strong>Seat number:</strong>
    <%= table.seat_number %>
  </p>

  <p>
    <strong>Is available:</strong>
    <%= table.is_available %>
  </p>

</div>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render "form", table: @table %>

<br>

<div>
  <%= link_to "Show this table", @table %> |
  <%= link_to "Back to tables", tables_path %>
</div>

app/views/tables/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tables</h1>

<div id="tables">
  <% @tables.each do |table| %>
    <%= render table %>
    <p>
      <%= link_to "Show this table", table %>
    </p>
  <% end %>
</div>

<%= link_to "New table", new_table_path %>

app/views/tables/new.html.erb
<h1>Add Table to <%= @restaurant.restaurant_name %></h1>
<%# render "form", table: @table %>
<%= render partial: 'form', locals: { restaurant: @restaurant, table: @table } %>
<br>
<div>
  <%= link_to "Back to My Restaurants", my_restaurants_path %>
</div>

app/views/tables/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @table %>

<div>
  <%= link_to "Edit this table", edit_table_path(@table) %> |
  <%= link_to "Back to tables", tables_path %>

  <%= button_to "Destroy this table", @table, method: :delete %>
</div>