config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  #Normal Routes
  
  root 'table_links#index'
  get 'table_links/about'

  #Modal Routes
  resources :reservations

  # resources :tables
  # resources :restaurants
  # resources :restaurants do
  #   resources :tables, only: [:new, :create, :destroy]
  # end

  resources :restaurants do
    resources :tables do
      resources :reservations, only: [:index, :new, :create]
    end
  end
  
  get 'my_restaurants', to: 'restaurants#my_restaurants'
  get 'my_reservations', to: 'reservations#my_reservations'
  
  #Devise Routes
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Neo Table Links', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About Us", table_links_about_path, class:"nav-link"%>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>

          <% if current_user.role == 'Admin' %>
            <li class="nav-item">
              <%= link_to "View All Users", users_index_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "View All Restaurants", restaurants_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "View All Reservations", reservations_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link text-danger', data: { turbo_method: :delete } %>
            </li>

            <% elsif current_user.role == 'Owner' %>
              <li class="nav-item">
                <%= link_to "Create A Restaurant", new_restaurant_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "My Restaurants", my_restaurants_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%# Link to View All Reservations Associated with their Restaurants %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link text-danger', data: { turbo_method: :delete } %>
            </li>
            <% elsif current_user.role == 'Customer' %>
              <li class="nav-item">
                <%= link_to "New Reservation", new_reservation_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "My Reservations", my_reservations_path, class: "nav-link"  %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link text-danger', data: { turbo_method: :delete } %>
              </li>
            <% else %>
              <li class="nav-item">
                <p>Seems you are an Unkown User</p>
              </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%# Bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <title>Neo Table Links</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= render  "layouts/header" %>
    <div class="container"> 
      <br/>
      <% if notice%>
        <%= render 'layouts/alerts'%>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>